-- Create syntax for TABLE 'finan_accounts'
CREATE TABLE `finan_accounts` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ToBeExported` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ExportTime` datetime ,
  `Exporter` varchar(30) NOT NULL DEFAULT '',
  `AcctNumber` int(9) NOT NULL DEFAULT '0',
  `Name` varchar(32) NOT NULL DEFAULT '',
  `Accounts_ID` int(9) unsigned DEFAULT NULL,
  `Types_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Description` varchar(60) NOT NULL DEFAULT '',
  `Notes` text NOT NULL,
  `Class` varchar(25) NOT NULL DEFAULT '',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Name` (`Name`),
  KEY `Types_ID` (`Types_ID`),
  KEY `Class` (`Class`),
  KEY `Active` (`Active`),
  KEY `AcctNumber` (`AcctNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_accounts_types'
CREATE TABLE `finan_accounts_types` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Name` char(30) NOT NULL DEFAULT '',
  `Category` char(30) NOT NULL DEFAULT '',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Name` (`Name`),
  KEY `Active` (`Active`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_billing'
CREATE TABLE `finan_billing` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ToBeExported` tinyint(1) NOT NULL DEFAULT '1',
  `ExportDate` datetime ,
  `Exporter` varchar(30) NOT NULL DEFAULT '',
  `Clients_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `ApplyAllJobs` smallint(1) unsigned NOT NULL DEFAULT '0',
  `Type` varchar(30) NOT NULL DEFAULT '',
  `Phone` varchar(24) NOT NULL DEFAULT '',
  `Email` char(85) NOT NULL ,
  `BillingNameOnCard` char(85) NOT NULL ,
  `BillingFirstName` varchar(25) NOT NULL DEFAULT '',
  `BillingLastName` varchar(35) NOT NULL DEFAULT '',
  `BillingAddress` varchar(50) NOT NULL DEFAULT '',
  `BillingCity` varchar(25) NOT NULL DEFAULT '',
  `BillingState` char(3) NOT NULL DEFAULT '',
  `BillingZip` varchar(10) NOT NULL DEFAULT '',
  `CCNumber` varchar(16) NOT NULL DEFAULT '',
  `CCExpYear` varchar(4) NOT NULL DEFAULT '',
  `CCExpMonth` char(2) NOT NULL DEFAULT '',
  `CCType` varchar(15) NOT NULL DEFAULT '',
  `CCBackThree` char(3) NOT NULL DEFAULT '',
  `Notes` text NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Active` (`Active`),
  KEY `Clients_ID` (`Clients_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_classes'
CREATE TABLE `finan_classes` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Classes_ID` int(11) unsigned DEFAULT NULL,
  `Name` char(30) NOT NULL,
  `Notes` char(255) NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Classes_ID` (`Classes_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2008-11-30 by Samuel';

-- Create syntax for TABLE 'finan_clients'
CREATE TABLE `finan_clients` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `ResourceType` tinyint(1) unsigned DEFAULT NULL,
  `SessionKey` char(32) NOT NULL,
  `ResourceToken` char(30) NOT NULL,
  `Active` tinyint(1) NOT NULL DEFAULT '1',
  `Statuses_ID` mediumint(4) unsigned NOT NULL,
  `ToBeExported` tinyint(1) NOT NULL DEFAULT '1',
  `Exporter` varchar(30) NOT NULL DEFAULT '',
  `ExportTime` datetime DEFAULT NULL,
  `Clients_ID` int(9) unsigned DEFAULT NULL,
  `ClientName` varchar(75) NOT NULL DEFAULT '',
  `ClientAccountNumber` char(30) NOT NULL,
  `CompanyName` char(75) NOT NULL,
  `Category` varchar(30) NOT NULL DEFAULT '',
  `Terms_ID` int(11) unsigned NOT NULL,
  `PrimarySalutation` char(20) NOT NULL,
  `PrimaryFirstName` varchar(35) NOT NULL DEFAULT '',
  `PrimaryMiddleName` char(35) NOT NULL,
  `PrimaryLastName` varchar(35) NOT NULL DEFAULT '',
  `Email` varchar(75) NOT NULL DEFAULT '',
  `EmailCC` char(85) NOT NULL COMMENT 'Added 2010-04-16 by Samuel',
  `MembershipType` char(35) DEFAULT NULL,
  `MembershipLevel` char(40) NOT NULL,
  `MembershipStart` date DEFAULT NULL,
  `MembershipEnd` date DEFAULT NULL,
  `ShowEmailPublicly` tinyint(1) NOT NULL DEFAULT '0',
  `UserName` varchar(30) DEFAULT NULL COMMENT 'Must be NULL for quasi resource',
  `Password` varchar(16) NOT NULL DEFAULT '',
  `PasswordMD5` varchar(32) NOT NULL,
  `Address1` varchar(75) NOT NULL DEFAULT '',
  `Address2` varchar(75) NOT NULL DEFAULT '',
  `City` varchar(45) NOT NULL DEFAULT '',
  `State` char(3) NOT NULL DEFAULT '',
  `Zip` varchar(10) NOT NULL DEFAULT '',
  `Country` char(3) NOT NULL DEFAULT 'USA',
  `ShippingAddress` varchar(128) NOT NULL DEFAULT '',
  `ShippingAddress2` char(75) NOT NULL COMMENT 'Added 2010-03-24 by Parker and Samuel',
  `ShippingCity` varchar(45) NOT NULL DEFAULT '',
  `ShippingState` char(3) NOT NULL DEFAULT '',
  `ShippingZip` varchar(10) NOT NULL DEFAULT '',
  `ShippingCountry` char(3) NOT NULL DEFAULT 'USA',
  `WebPage` char(255) NOT NULL,
  `ContactPage` text NOT NULL,
  `LandingPage` text NOT NULL,
  `MetaTitle` char(255) NOT NULL COMMENT 'Added 2010-06-29 by Samuel',
  `Description` text NOT NULL COMMENT 'Added 2010-06-29 by Samuel',
  `Keywords` text NOT NULL COMMENT 'Added 2010-06-29 by Samuel',
  `ShowCard` char(20) NOT NULL COMMENT 'Added 2010-06-29 by Samuel',
  `Phone` varchar(24) NOT NULL DEFAULT '',
  `Phone2` char(24) NOT NULL COMMENT 'Added 2010-04-16 by Samuel',
  `Mobile` varchar(24) NOT NULL DEFAULT '',
  `Fax` varchar(24) NOT NULL DEFAULT '',
  `Referral` varchar(30) NOT NULL DEFAULT '',
  `Notes` text NOT NULL,
  `WRO_Corporate` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UserName` (`UserName`),
  KEY `Clients_ID` (`Clients_ID`),
  KEY `ClientName` (`ClientName`),
  KEY `ResourceType` (`ResourceType`),
  KEY `Active` (`Active`),
  KEY `Statuses_ID` (`Statuses_ID`),
  KEY `PrimaryLastName` (`PrimaryLastName`),
  KEY `PrimaryFirstName` (`PrimaryFirstName`),
  KEY `Address1` (`Address1`),
  KEY `City` (`City`),
  KEY `State` (`State`)
) ENGINE=MyISAM AUTO_INCREMENT=1434 DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_clients_statuses'
CREATE TABLE `finan_clients_statuses` (
  `ID` mediumint(4) unsigned NOT NULL,
  `Name` char(45) NOT NULL,
  `ColorCode` char(32) NOT NULL,
  `StatusHandle` char(45) NOT NULL,
  `Notes` char(255) NOT NULL,
  `EditDate` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `Name` (`Name`),
  KEY `StatusHandle` (`StatusHandle`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2008-07-08 by Samuel';

-- Create syntax for TABLE 'finan_clients_websites'
CREATE TABLE `finan_clients_websites` (
  `ID` int(9) unsigned NOT NULL,
  `PageActive` tinyint(1) NOT NULL DEFAULT '1',
  `PageName` char(20) NOT NULL DEFAULT 'default',
  `ShowCard` char(15) NOT NULL,
  `Content` longtext NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY(`PageName`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_ClientsCategories'
CREATE TABLE `finan_ClientsCategories` (
  `Clients_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `Categories_ID` char(45) NOT NULL DEFAULT '0',
  `Type` char(30) NOT NULL DEFAULT '',
  `Notes` char(70) NOT NULL DEFAULT '',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Clients_ID`,`Categories_ID`),
  KEY `Type` (`Type`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_ClientsContacts'
CREATE TABLE `finan_ClientsContacts` (
  `Clients_ID` int(7) unsigned NOT NULL DEFAULT '0',
  `Contacts_ID` int(7) unsigned NOT NULL DEFAULT '0',
  `Type` char(30) NOT NULL DEFAULT '',
  `Notes` char(128) NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Clients_ID`,`Contacts_ID`),
  KEY `Clients_ID` (`Clients_ID`),
  KEY `Contacts_ID` (`Contacts_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2006-02-15 by Sam';

-- Create syntax for TABLE 'finan_headers'
CREATE TABLE `finan_headers` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `HeaderType` enum('Invoice','Cash Sale','Payment','Deposit','Check','General Journal') NOT NULL,
  `HeaderStatus` char(7) NOT NULL DEFAULT 'Current' ,
  `HeaderFlag` enum('','Discrepancy') NOT NULL,
  `HeaderDate` date ,
  `HeaderNumber` char(20) DEFAULT NULL,
  `ResourceType` tinyint(1) unsigned DEFAULT NULL COMMENT 'For quasi resource headers',
  `ResourceToken` char(16) DEFAULT NULL COMMENT 'For quasi resource headers',
  `SessionKey` char(32) NOT NULL,
  `ToBeExported` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ExportTime` datetime ,
  `Exporter` char(20) NOT NULL DEFAULT '',
  `ToBePrinted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `Clients_ID` int(11) unsigned DEFAULT NULL,
  `Contacts_ID` int(9) DEFAULT NULL,
  `Accounts_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Classes_ID` int(11) unsigned DEFAULT NULL,
  `Notes` char(75) NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Accounts_ID` (`Accounts_ID`),
  KEY `Classes_ID` (`Classes_ID`),
  KEY `SessionKey` (`SessionKey`),
  KEY `HeaderType` (`HeaderType`),
  KEY `HeaderDate` (`HeaderDate`),
  KEY `HeaderNumber` (`HeaderNumber`),
  KEY `Clients_ID` (`Clients_ID`),
  KEY `Contacts_ID` (`Contacts_ID`),
  KEY `ResourceType` (`ResourceType`),
  KEY `ResourceToken` (`ResourceToken`),
  KEY `HeaderStatus` (`HeaderStatus`),
  KEY `HeaderFlag` (`HeaderFlag`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_hours'
CREATE TABLE `finan_hours` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Timesheets_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Items_ID` int(9) unsigned DEFAULT NULL,
  `Clients_ID` int(9) unsigned DEFAULT NULL,
  `Projects_ID` int(11) unsigned NOT NULL ,
  `Contacts_ID` int(11) unsigned NOT NULL ,
  `StartTime` datetime ,
  `EndTime` datetime ,
  `TotalHours` float(7,2) unsigned NOT NULL ,
  `BillableHours` float(7,2) unsigned NOT NULL ,
  `PayableHours` float(7,2) unsigned NOT NULL ,
  `BillableFlag` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `Description` text NOT NULL,
  `BillingDescription` text NOT NULL,
  `Achievements` text NOT NULL,
  `Comments` text NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Timesheets_ID` (`Timesheets_ID`),
  KEY `Items_ID` (`Items_ID`),
  KEY `Clients_ID` (`Clients_ID`),
  KEY `TotalHours` (`TotalHours`),
  KEY `Projects_ID` (`Projects_ID`),
  KEY `StartTime` (`StartTime`),
  KEY `EndTime` (`EndTime`),
  KEY `Contacts_ID` (`Contacts_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_invoices'
CREATE TABLE `finan_invoices` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) DEFAULT '1',
  `ToBeEmailed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `InvoiceDate` date ,
  `SessionKey` varchar(32) NOT NULL DEFAULT '',
  `EffectiveDate` date DEFAULT NULL,
  `EffectiveDateEnd` date DEFAULT NULL,
  `InvoiceNumber` varchar(10) DEFAULT NULL,
  `ToBeExported` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ExportTime` datetime ,
  `Exporter` varchar(30) NOT NULL DEFAULT '',
  `ToBePrinted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `Category` varchar(30) NOT NULL DEFAULT '',
  `Clients_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Contacts_ID` int(11) unsigned NOT NULL,
  `Billing_ID` int(9) unsigned DEFAULT NULL,
  `Classes_ID` int(11) unsigned DEFAULT NULL,
  `Accounts_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `ShippingFirstName` varchar(25) NOT NULL DEFAULT '',
  `ShippingLastName` varchar(35) NOT NULL DEFAULT '',
  `ShippingCompany` varchar(50) NOT NULL DEFAULT '',
  `ShippingAddress` varchar(60) NOT NULL DEFAULT '',
  `ShippingAddress2` varchar(60) NOT NULL DEFAULT '',
  `ShippingCity` varchar(30) NOT NULL DEFAULT '',
  `ShippingState` char(3) NOT NULL DEFAULT '',
  `ShippingZip` varchar(10) NOT NULL DEFAULT '',
  `ShippingCountry` char(3) NOT NULL DEFAULT 'USA',
  `ShippingPhone` varchar(24) NOT NULL DEFAULT '',
  `ShippingEmail` varchar(60) NOT NULL DEFAULT '',
  `ShippingNotes` text NOT NULL,
  `ShippingStatus` tinyint(3) DEFAULT NULL,
  `BillingFirstName` varchar(25) NOT NULL DEFAULT '',
  `BillingLastName` varchar(35) NOT NULL DEFAULT '',
  `BillingAddress` text NOT NULL,
  `BillingCity` varchar(30) NOT NULL DEFAULT '',
  `BillingState` char(3) NOT NULL DEFAULT '',
  `BillingZip` varchar(10) NOT NULL DEFAULT '',
  `BillingPhone` varchar(24) NOT NULL DEFAULT '',
  `BillingEmail` varchar(50) NOT NULL DEFAULT '',
  `BillingStatus` tinyint(3) DEFAULT NULL,
  `PONumber` varchar(30) NOT NULL DEFAULT '',
  `CCConfNumber` varchar(20) NOT NULL DEFAULT '',
  `Terms_ID` int(9) unsigned DEFAULT NULL,
  `Wholesale` tinyint(30) unsigned NOT NULL DEFAULT '0',
  `ShippingMethod` char(3) NOT NULL DEFAULT '',
  `ShippingResidential` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ShippingTrackingNumber` varchar(30) NOT NULL DEFAULT '',
  `Referral` varchar(40) NOT NULL DEFAULT '',
  `Term` varchar(40) NOT NULL DEFAULT '',
  `OrderTotal` float(7,2) NOT NULL,
  `Comments` text NOT NULL,
  `Notes` text NOT NULL,
  `ClientMessage` text NOT NULL,
  `InvoiceSummary` text NOT NULL,
  `BillingCountry` char(3) NOT NULL DEFAULT 'USA',
  `Headers_ID` int(11) unsigned NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Active` (`Active`),
  KEY `SessionKey` (`SessionKey`),
  KEY `InvoiceNumber` (`InvoiceNumber`),
  KEY `Clients_ID` (`Clients_ID`),
  KEY `Billing_ID` (`Billing_ID`),
  KEY `Accounts_ID` (`Accounts_ID`),
  KEY `ShippingFirstName` (`ShippingFirstName`),
  KEY `ShippingLastName` (`ShippingLastName`),
  KEY `Contacts_ID` (`Contacts_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_items'
CREATE TABLE `finan_items` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `OutOfStock` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ToBeExported` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ExportDate` datetime ,
  `Exporter` varchar(30) NOT NULL,
  `InStock` smallint(5) unsigned NOT NULL DEFAULT '1',
  `ReorderPt` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Ourgroup_ID` int(7) unsigned NOT NULL,
  `Schemas_ID` mediumint(4) unsigned NOT NULL DEFAULT '0',
  `GroupLeader` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `SuperSKU` varchar(75) NOT NULL,
  `Model` char(75) NOT NULL,
  `SKU` varchar(128) DEFAULT NULL COMMENT 'null OK',
  `ManufacturerSKU` varchar(75) NOT NULL,
  `UPC` varchar(18) NOT NULL DEFAULT '',
  `RWB` char(1) NOT NULL DEFAULT 'B',
  `Priority` mediumint(5) unsigned NOT NULL,
  `Category` varchar(60) NOT NULL,
  `SubCategory` varchar(60) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Caption` char(255) NOT NULL,
  `Manufacturers_ID` int(11) unsigned NOT NULL,
  `Manufacturer` varchar(75) NOT NULL DEFAULT '',
  `Brand` char(75) NOT NULL,
  `Vendors_ID` int(11) unsigned NOT NULL,
  `Vendor` char(75) NOT NULL,
  `Description` longtext NOT NULL,
  `LongDescription` longtext NOT NULL,
  `Function` char(75) NOT NULL COMMENT 'Added back in 2009-09-03',
  `SubFunction` char(75) NOT NULL COMMENT 'Added back in 2009-09-03',
  `ItemFootnote` text NOT NULL,
  `Notes` text NOT NULL,
  `PurchasePrice` float(6,2) NOT NULL DEFAULT '0.00',
  `WholesalePrice` float(6,2) NOT NULL DEFAULT '0.00',
  `UnitPrice` float(7,3) NOT NULL DEFAULT '0.000',
  `UnitPrice2` float(7,3) DEFAULT NULL,
  `Taxable` float(5,3) NOT NULL DEFAULT '0.000',
  `Taxable2` float(5,3) DEFAULT NULL,
  `Special` float(7,5) unsigned NOT NULL,
  `Featured` tinyint(1) unsigned NOT NULL,
  `ListPrice` float(7,3) NOT NULL DEFAULT '0.000',
  `Length` float(5,2) unsigned NOT NULL DEFAULT '0.00',
  `Width` float(5,2) unsigned NOT NULL DEFAULT '0.00',
  `Depth` float(5,2) unsigned NOT NULL DEFAULT '0.00',
  `Weight` float(5,2) NOT NULL DEFAULT '0.00',
  `Shippers_ID` int(11) NOT NULL,
  `Shipmethods_ID` int(11) unsigned DEFAULT NULL COMMENT 'Added to template 2012-07-08',
  `Accounts_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `AssetAccounts_ID` int(11) unsigned NOT NULL,
  `COGSAccounts_ID` int(11) unsigned NOT NULL,
  `Classes_ID` int(11) unsigned NOT NULL,
  `Type` varchar(30) NOT NULL DEFAULT 'Non-inventory part',
  `IsPassedThrough` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `Items_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Keywords` text NOT NULL,
  `ExpirationDate` date NOT NULL,
  `Edition` int(3) NOT NULL,
  `Theme` varchar(40) NOT NULL DEFAULT '',
  `SubTheme` varchar(40) NOT NULL DEFAULT '',
  `BreakPrice` float(6,2) unsigned NOT NULL DEFAULT '0.00',
  `UM` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PK` smallint(5) unsigned NOT NULL DEFAULT '1',
  `ResourceType` tinyint(1) unsigned DEFAULT NULL,
  `ResourceToken` char(30) NOT NULL,
  `SessionKey` char(32) NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Schemas_ID` (`Schemas_ID`),
  KEY `GroupLeader` (`GroupLeader`),
  KEY `Priority` (`Priority`),
  KEY `Vendor` (`Vendor`),
  KEY `Manufacturers_ID` (`Manufacturers_ID`),
  KEY `Items_ID` (`Items_ID`),
  KEY `Shippers_ID` (`Shippers_ID`),
  KEY `Accounts_ID` (`Accounts_ID`),
  KEY `OutOfStock` (`OutOfStock`),
  KEY `AssetAccounts_ID` (`AssetAccounts_ID`),
  KEY `COGSAccounts_ID` (`COGSAccounts_ID`),
  KEY `Classes_ID` (`Classes_ID`),
  KEY `Vendors_ID` (`Vendors_ID`),
  KEY `Shipmethods_ID` (`Shipmethods_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COMMENT='Moved over 2008-12-18 to make room for new';

-- Create syntax for TABLE 'finan_items_categories'
CREATE TABLE `finan_items_categories` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Name` varchar(40) NOT NULL DEFAULT '',
  `Caption` char(255) NOT NULL,
  `Heading` text NOT NULL,
  `Description` text NOT NULL,
  `Keywords` text NOT NULL,
  `Priority` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_items_packages'
CREATE TABLE `finan_items_packages` (
  `Items_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `OverallDescription` longtext NOT NULL,
  `OverallLongDescription` longtext NOT NULL,
  `ShowItemPicture` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `PricingType` enum('No Price Change','Specific Package Price','Auto Discount') NOT NULL,
  `PriceValue` float(7,2) NOT NULL,
  `AutoUpdatePrice` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`Items_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_items_related'
CREATE TABLE `finan_items_related` (
  `Parent_ID` int(11) unsigned NOT NULL,
  `Child_ID` int(11) unsigned NOT NULL,
  `Reflexive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ForwardComments` text NOT NULL,
  `BackComments` text NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Parent_ID`,`Child_ID`),
  KEY `Reflexive` (`Reflexive`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2008-01-14 by Samuel';

-- Create syntax for TABLE 'finan_items_subcategories'
CREATE TABLE `finan_items_subcategories` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Category` char(55) NOT NULL,
  `SubCategory` char(55) NOT NULL,
  `Title` char(255) NOT NULL,
  `Description` text NOT NULL,
  `Keywords` text NOT NULL,
  `Heading` text NOT NULL,
  `Priority` mediumint(4) unsigned NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CategorySubcategory` (`Category`,`SubCategory`),
  KEY `Title` (`Title`),
  KEY `Priority` (`Priority`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_ItemsItems'
CREATE TABLE `finan_ItemsItems` (
  `ParentItems_ID` int(11) unsigned NOT NULL,
  `ChildItems_ID` int(11) unsigned NOT NULL,
  `Idx` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `Quantity` float(7,2) unsigned NOT NULL DEFAULT '1.00',
  `BonusItem` tinyint(1) unsigned NOT NULL,
  `PricingType` enum('Free','Price','Percent') NOT NULL,
  `PriceValue` float(7,2) NOT NULL,
  `OverrideName` char(255) NOT NULL,
  `OverrideDescription` text NOT NULL,
  `OverrideLongDescription` text NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ParentItems_ID`,`ChildItems_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2008-09-17 by Samuel';

-- Create syntax for TABLE 'finan_manufacturers'
CREATE TABLE `finan_manufacturers` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `FirstName` varchar(30) NOT NULL,
  `LastName` varchar(30) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Phone` varchar(20) NOT NULL,
  `Address` varchar(200) NOT NULL,
  `City` varchar(50) NOT NULL,
  `State` varchar(2) NOT NULL,
  `ZIP` int(5) NOT NULL,
  `Country` varchar(100) NOT NULL,
  `URL` varchar(255) NOT NULL,
  `ShowDescription` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Description` longtext NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(30) NOT NULL DEFAULT '{RB_ACCTNAME}',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `Name` (`Name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_payments'
CREATE TABLE `finan_payments` (
  `Headers_ID` int(11) unsigned NOT NULL COMMENT '1-to-1 mapping with finan_headers; NEVER autoincrement',
  `Types_ID` int(11) unsigned NOT NULL DEFAULT '0',
  `CkConfirmationNumber` varchar(15) NOT NULL DEFAULT '',
  `Category` varchar(30) NOT NULL DEFAULT '',
  `Notes` text,
  PRIMARY KEY (`Headers_ID`),
  KEY `Paymenttypes_ID` (`Types_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_payments_types'
CREATE TABLE `finan_payments_types` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ToBeExported` tinyint(1) NOT NULL DEFAULT '1',
  `ExportTime` datetime ,
  `Exporter` char(30) NOT NULL DEFAULT '',
  `Name` char(30) NOT NULL DEFAULT '',
  `EFTAccounts_ID` int(7) unsigned NOT NULL DEFAULT '0',
  `Notes` char(75) NOT NULL DEFAULT '',
  `CreateDate` datetime ,
  `Creator` char(30) NOT NULL DEFAULT '{RB_ACCTNAME}' ,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` char(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_projects'
CREATE TABLE `finan_projects` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Clients_ID` int(11) unsigned NOT NULL,
  `Name` char(75) NOT NULL,
  `Description` char(255) NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ClientProject` (`Clients_ID`,`Name`),
  KEY `Clients_ID` (`Clients_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2010-02-01 by Samuel; interlocks with Clients';

-- Create syntax for TABLE 'finan_salesreps'
CREATE TABLE `finan_salesreps` (
  `Contacts_ID` int(11) unsigned NOT NULL,
  `RepCode` varchar(3) NOT NULL,
  `Department` varchar(75) NOT NULL,
  `Phone` varchar(20) NOT NULL,
  `CreateDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Creator` varchar(40) NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` varchar(40) NOT NULL,
  PRIMARY KEY (`Contacts_ID`),
  UNIQUE KEY `RepCode` (`RepCode`),
  KEY `Department` (`Department`),
  KEY `Phone` (`Phone`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_shippers'
CREATE TABLE `finan_shippers` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `PrimaryShipper` bit(1) DEFAULT NULL COMMENT 'Only one record in the table can contain this; created automatically if not present',
  `Manufacturers_ID` int(11) unsigned DEFAULT NULL COMMENT 'Present if the shipper represents a single manufacturer',
  `Name` char(35) NOT NULL,
  `Description` char(255) NOT NULL,
  `Methods` char(30) NOT NULL,
  `DefaultMethod` tinyint(3) unsigned NOT NULL,
  `OriginTitle` char(75) NOT NULL,
  `OriginAddress` char(75) NOT NULL,
  `OriginCity` char(45) NOT NULL,
  `OriginState` char(3) NOT NULL,
  `OriginZip` int(5) unsigned NOT NULL,
  `OriginCountry` char(3) NOT NULL DEFAULT 'USA',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PrimaryShipper` (`PrimaryShipper`),
  KEY `DefaultMethod` (`DefaultMethod`),
  KEY `Manufacturers_ID` (`Manufacturers_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ;

-- Create syntax for TABLE 'finan_shipping'
CREATE TABLE `finan_shipping` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Shippers_ID` int(11) unsigned NOT NULL,
  `Shipped` tinyint(1) unsigned NOT NULL COMMENT 'boolean: whether the order was shipped or not',
  `ShipDate` datetime NOT NULL,
  `ReceiptNumber` char(45) NOT NULL,
  `TrackingNumber` char(45) NOT NULL,
  `Carrier` char(45) NOT NULL,
  `Method` char(45) NOT NULL,
  `Residential` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Cost` float(6,2) NOT NULL,
  `AdditionalWeight` float(7,2) NOT NULL,
  `OriginZip` char(10) NOT NULL,
  `DestinationZip` char(10) NOT NULL,
  `Notes` char(255) NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `Carrier` (`Carrier`),
  KEY `Shippers_ID` (`Shippers_ID`),
  KEY `Shipped` (`Shipped`),
  KEY `ShippingIDNumber` (`ReceiptNumber`),
  KEY `TrackingNumber` (`TrackingNumber`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ;

-- Create syntax for TABLE 'finan_terms'
CREATE TABLE `finan_terms` (
  `ID` mediumint(7) NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `ToBeExported` tinyint(1) NOT NULL DEFAULT '1',
  `ExportDate` datetime ,
  `Exporter` char(30) NOT NULL DEFAULT '',
  `Name` char(30) NOT NULL DEFAULT '',
  `Type` smallint(2) unsigned NOT NULL DEFAULT '0',
  `DaysOut` mediumint(3) NOT NULL DEFAULT '0',
  `DiscountPercentage` float(4,3) DEFAULT NULL,
  `DiscountPercentageWithin` mediumint(3) NOT NULL DEFAULT '0',
  `DayOfMonth` smallint(2) unsigned NOT NULL DEFAULT '0',
  `DayOfMonthProximity` smallint(2) unsigned NOT NULL DEFAULT '0',
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` char(30) NOT NULL DEFAULT '{RB_ACCTNAME}' ,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` char(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_transactions'
CREATE TABLE `finan_transactions` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Idx` mediumint(4) unsigned NOT NULL DEFAULT '0',
  `Headers_ID` int(11) unsigned NOT NULL COMMENT 'Financial 2.0',
  `Items_ID` int(9) unsigned DEFAULT NULL,
  `Accounts_ID` int(9) unsigned NOT NULL DEFAULT '0',
  `Classes_ID` int(11) unsigned NOT NULL,
  `Hours_ID` int(9) unsigned DEFAULT NULL,
  `Shipping_ID` int(11) unsigned DEFAULT NULL,
  `Name` varchar(45) NOT NULL DEFAULT '',
  `Description` text,
  `SKU` varchar(25) NOT NULL DEFAULT '',
  `UPC` varchar(25) NOT NULL DEFAULT '',
  `Weight` float(8,3) unsigned DEFAULT NULL,
  `Quantity` float(10,4) DEFAULT NULL,
  `UnitPrice` float(11,2) DEFAULT NULL,
  `Percentage` float(8,5) DEFAULT NULL,
  `Type` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `Extension` float(11,2) DEFAULT NULL,
  `Taxable` smallint(2) unsigned NOT NULL DEFAULT '0',
  `Wholesale` smallint(2) unsigned NOT NULL DEFAULT '0',
  `CreateDate` datetime NOT NULL,
  `Creator` char(20) NOT NULL,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` char(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `Shipping_ID` (`Shipping_ID`),
  KEY `Headers_ID` (`Headers_ID`),
  KEY `Classes_ID` (`Classes_ID`),
  KEY `Type` (`Type`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'finan_TransactionsHours'
CREATE TABLE `finan_TransactionsHours` (
  `Transactions_ID` int(11) unsigned NOT NULL,
  `Hours_ID` int(11) unsigned NOT NULL,
  `Application` enum('Billing','Timesheet') NOT NULL DEFAULT 'Billing',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Notes` char(75) NOT NULL,
  PRIMARY KEY (`Transactions_ID`,`Hours_ID`,`Application`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Created 2010-02-01 by Samuel; better join method for hours/t';

-- Create syntax for TABLE 'finan_TransactionsTransactions'
CREATE TABLE `finan_TransactionsTransactions` (
  `ParentTransactions_ID` int(11) unsigned NOT NULL,
  `ChildTransactions_ID` int(11) unsigned NOT NULL,
  `AmountApplied` float(10,2) NOT NULL,
  `Type` char(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Payment, more later',
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ParentTransactions_ID`,`ChildTransactions_ID`),
  KEY `AmountApplied` (`AmountApplied`),
  KEY `Type` (`Type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Created 2011-01-05; relationship between two transactions';

-- Create syntax for TABLE 'finan_vendors'
CREATE TABLE `finan_vendors` (
  `ID` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `Active` tinyint(1) NOT NULL DEFAULT '1',
  `ToBeExported` tinyint(1) NOT NULL DEFAULT '1',
  `Exporter` varchar(30) NOT NULL DEFAULT '',
  `ExportTime` datetime ,
  `ClientName` varchar(75) NOT NULL,
  `ClientAccountNumber` char(30) NOT NULL,
  `CompanyName` char(75) NOT NULL,
  `Type` varchar(30) NOT NULL,
  `Terms_ID` int(11) unsigned NOT NULL,
  `CreditLimit` float(10,2) unsigned NOT NULL,
  `PrimarySalutation` char(20) NOT NULL,
  `PrimaryFirstName` varchar(35) NOT NULL DEFAULT '',
  `PrimaryMiddleName` char(35) NOT NULL,
  `PrimaryLastName` varchar(35) NOT NULL DEFAULT '',
  `Email` varchar(75) NOT NULL DEFAULT '',
  `UserName` varchar(30) NOT NULL DEFAULT '',
  `Password` varchar(16) NOT NULL DEFAULT '',
  `PasswordMD5` varchar(32) NOT NULL,
  `Address1` varchar(75) NOT NULL DEFAULT '',
  `Address2` varchar(75) NOT NULL DEFAULT '',
  `City` varchar(45) NOT NULL DEFAULT '',
  `State` char(3) NOT NULL DEFAULT '',
  `Zip` varchar(10) NOT NULL DEFAULT '',
  `Country` char(3) NOT NULL DEFAULT 'USA',
  `WebPage` char(255) NOT NULL,
  `Phone` varchar(24) NOT NULL DEFAULT '',
  `Phone2` char(25) NOT NULL,
  `Mobile` varchar(24) NOT NULL DEFAULT '',
  `Fax` varchar(24) NOT NULL DEFAULT '',
  `Notes` text NOT NULL,
  `CreateDate` datetime DEFAULT CURRENT_TIMESTAMP,
  `Creator` char(30) NOT NULL DEFAULT '{RB_ACCTNAME}' ,
  `EditDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Editor` char(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;